apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-aiqk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-aiqk
    app.kubernetes.io/part-of: tkrw-pr714-0075-0027-app
  name: devfile-sample-aiqk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-aiqk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-aiqk
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0027-tenant/tkrw-pr714-0075-0027-app/devfile-sample-aiqk@sha256:30ac6d1475220f316ce6a3cf12df52925521bdcc0f3ae021948e9aad3d851632
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
